/* soapTester.cpp
   Generated by gSOAP 2.8.114 for onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/
/*
   Stand-alone server auto-test code:
   Takes request from standard input or over TCP/IP socket and returns
response to standard output or socket

   Compile:
   cc soapTester.c soapServer.c soapC.c stdsoap2.c

   Command line usage with redirect over stdin/out:
   > ./a.out < SomeTest.req.xml
   > ./a.out 12288 < SomeTest.req.xml
     Note: 12288 = SOAP_XML_INDENT | SOAP_XML_STRICT (see codes in stdsoap2.h)
   Command line usage to start server at port 8080:
   > a.out 12288 8080
*/

#include "soapH.h"
#include "wsdd.nsmap"

#include <stdio.h>
#include <stdlib.h>
#include "wsddapi.h"
#include<string.h>	//memset
#include<errno.h>	//errno
#include<sys/socket.h>
#include<netdb.h>
#include<ifaddrs.h>
#include<unistd.h>


/*WS-Discovery specialization address and port of UDP*/
#define MULTICAST_GROUP ("239.255.255.250")  
#define PORT (3702) 

char* get_address();

char  g_scopes[] = "onvif://www.onvif.org/Profile/Streaming \
				onvif://www.onvif.org/model/C5F0S7Z0N1P0L0V0 \
				onvif://www.onvif.org/name/IPCAM \
				onvif://www.onvif.org/location/country/Vietnam"; 

const char* host = "239.255.255.250";	
int port = 3702;
int port_onvif;

int main(int argc, char** argv)
{
	if(argc >= 2)
	{
		port_onvif = atoi(argv[1]);
	}else{
		port_onvif = 8000;
	}
	printf("%d\n",port_onvif);
	
	struct soap* serv = soap_new1(SOAP_IO_UDP | SOAP_IO_KEEPALIVE); 
	serv->bind_flags=SO_REUSEADDR;
	serv->connect_flags = SO_BROADCAST; 
	if (!soap_valid_socket(soap_bind(serv, NULL, port, 1000)))
	{
		soap_print_fault(serv, stderr);
		exit(1);
	}	

	if (MULTICAST_GROUP) { 
		struct ip_mreq mreq;
		mreq.imr_multiaddr.s_addr = inet_addr(MULTICAST_GROUP);
		mreq.imr_interface.s_addr = htonl(INADDR_ANY);
		if (setsockopt(serv->socket, IPPROTO_IP, IP_ADD_MEMBERSHIP, &mreq, sizeof(mreq)) < 0) {
			printf("setsockopt failed\n");
	      		exit(-1);
		}
	}
	


	// signal(SIGINT, &sighandler);
	while (1)
	{
		soap_wsdd_listen(serv, -1000);
	}


	return 0;
}


void wsdd_event_Hello(struct soap *soap, unsigned int InstanceId, const char *SequenceId, unsigned int MessageNumber, const char *MessageID, const char *RelatesTo, const char *EndpointReference, const char *Types, const char *Scopes, const char *MatchBy, const char *XAddrs, unsigned int MetadataVersion)
{ }

void wsdd_event_Bye(struct soap *soap, unsigned int InstanceId, const char *SequenceId, unsigned int MessageNumber, const char *MessageID, const char *RelatesTo, const char *EndpointReference, const char *Types, const char *Scopes, const char *MatchBy, const char *XAddrs, unsigned int *MetadataVersion)
{ }

soap_wsdd_mode wsdd_event_Probe(struct soap *soap, const char *MessageID,
		const char *ReplyTo, const char *Types, const char *Scopes,
		const char *MatchBy, struct wsdd__ProbeMatchesType *matches) {
	printf("%s,%d\n", __FUNCTION__, __LINE__);
	printf("MessageID:%s\n", MessageID);
	printf("ReplyTo:%s\n", ReplyTo);
	printf("Types:%s\n", Types);
	printf("Scopes:%s\n", Scopes);
	printf("MatchBy:%s\n", MatchBy);
	printf("\n");


	// soap->header->wsa__RelatesTo = (struct wsa__Relationship*) soap_malloc(
	// 		soap, sizeof(struct wsa__Relationship));

	// if (soap->header->wsa__ReplyTo) {
	// 	soap->header->wsa__To = soap->header->wsa__ReplyTo->Address;
	// } else {
	// 	soap->header->wsa__To = NULL;
	// }
	// soap->header->wsa__RelatesTo->__item = soap->header->wsa__MessageID;
	// soap->header->wsa__RelatesTo->RelationshipType = NULL;
	// soap->header->wsa__RelatesTo->__anyAttribute = NULL;
	// soap->header->wsa__Action = "http://schemas.xmlsoap.org/ws/2005/04/discovery/ProbeMatches";
	// soap->header->wsa__ReplyTo = NULL;

	// char* address = get_address();
	soap_wsdd_init_ProbeMatches(soap, matches);
	soap_wsdd_add_ProbeMatch(soap, matches,
				"urn:uuid:464A4854-4656-5242-4530-313035394100",
				"tdn:NetworkVideoTransmitter", g_scopes,
				NULL,
				"address",
				10);

	return SOAP_WSDD_MANAGED;
}

void wsdd_event_ProbeMatches(struct soap *soap, unsigned int InstanceId, const char *SequenceId, unsigned int MessageNumber, const char *MessageID, const char *RelatesTo, struct wsdd__ProbeMatchesType *ProbeMatches)
{ }

soap_wsdd_mode wsdd_event_Resolve(struct soap *soap, const char *MessageID, const char *ReplyTo, const char *EndpointReference, struct wsdd__ResolveMatchType *match)
{
  return SOAP_WSDD_ADHOC;
}

void wsdd_event_ResolveMatches(struct soap *soap, unsigned int InstanceId, const char * SequenceId, unsigned int MessageNumber, const char *MessageID, const char *RelatesTo, struct wsdd__ResolveMatchType *match)
{ }



/** Auto-test server operation SOAP_ENV__Fault */
int SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail)
{
	(void)soap; /* appease -Wall -Werror */
	return SOAP_OK;
}





// /** Auto-test server operation __wsdd__Hello */
// int __wsdd__Hello(struct soap *soap, struct wsdd__HelloType *wsdd__Hello)
// {
// 	(void)soap; /* appease -Wall -Werror */
// 	return SOAP_OK;
// }


// /** Auto-test server operation __wsdd__Bye */
// int __wsdd__Bye(struct soap *soap, struct wsdd__ByeType *wsdd__Bye)
// {
// 	(void)soap; /* appease -Wall -Werror */
// 	return SOAP_OK;
// }


// /** Auto-test server operation __wsdd__Probe */
// int __wsdd__Probe(struct soap *soap, struct wsdd__ProbeType *wsdd__Probe)
// {
// 	(void)soap; /* appease -Wall -Werror */
// 	return SOAP_OK;
// }


// /** Auto-test server operation __wsdd__ProbeMatches */
// int __wsdd__ProbeMatches(struct soap *soap, struct wsdd__ProbeMatchesType *wsdd__ProbeMatches)
// {
// 	(void)soap; /* appease -Wall -Werror */
// 	return SOAP_OK;
// }


// /** Auto-test server operation __wsdd__Resolve */
// int __wsdd__Resolve(struct soap *soap, struct wsdd__ResolveType *wsdd__Resolve)
// {
// 	(void)soap; /* appease -Wall -Werror */
// 	return SOAP_OK;
// }


// /** Auto-test server operation __wsdd__ResolveMatches */
// int __wsdd__ResolveMatches(struct soap *soap, struct wsdd__ResolveMatchesType *wsdd__ResolveMatches)
// {
// 	(void)soap; /* appease -Wall -Werror */
// 	return SOAP_OK;
// }




char* get_address(){
	FILE *f;
    char line[100] , *p , *c;
    f = fopen("/proc/net/route" , "r");
    while(fgets(line , 100 , f))
    {
		p = strtok(line , " \t");
		c = strtok(NULL , " \t");
		if(p!=NULL && c!=NULL)
		{
			if(strcmp(c , "00000000") == 0)
			{
				printf("Default interface is : %s \n" , p);
				break;
			}
		}
	}
    //which family do we require , AF_INET or AF_INET6
    int fm = AF_INET;
    struct ifaddrs *ifaddr, *ifa;
	int family , s;
	char host[NI_MAXHOST];

	if (getifaddrs(&ifaddr) == -1) 
	{
		perror("getifaddrs");
		exit(EXIT_FAILURE);
	}
	//Walk through linked list, maintaining head pointer so we can free list later
	for (ifa = ifaddr; ifa != NULL; ifa = ifa->ifa_next) 
	{
		if (ifa->ifa_addr == NULL)
		{
			continue;
		}
		family = ifa->ifa_addr->sa_family;
		if(strcmp( ifa->ifa_name , p) == 0)
		{
			if (family == fm) 
			{
				s = getnameinfo( ifa->ifa_addr, (family == AF_INET) ? sizeof(struct sockaddr_in) : sizeof(struct sockaddr_in6) , host , NI_MAXHOST , NULL , 0 , NI_NUMERICHOST);
				if (s != 0) 
				{
					printf("getnameinfo() failed: %s\n", gai_strerror(s));
					exit(EXIT_FAILURE);
				}
				printf("address: %s", host);
			}
			printf("\n");
		}
	}
	freeifaddrs(ifaddr);

	int ans = 140;
    int x = port_onvif;
    int size = 0;
    while ( x ) {
       x=x/10;
       size++;
    }
    char port_array[size];
    for (int i = size - 1; x ; x = x/10, i-- ) {
       port_array[i] = x % 10;
    }


	// char* local_ip = malloc(500);
	char* local_ip;
	strcpy(local_ip, (char*)"");
	strcat(local_ip, (char*)"http://");
	strcat(local_ip, (char*)host);
	strcat(local_ip, (char*)":");
	strcat(local_ip, (char*)port_array);
	strcat(local_ip, (char*)"/onvif/device_service");
	printf("address: %s \n", local_ip);
	return local_ip;
}



/** Auto-test server operation __tdn__Hello */
int __tdn__Hello(struct soap *soap, struct wsdd__HelloType tdn__Hello, struct wsdd__ResolveType &tdn__HelloResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tdn__Bye */
int __tdn__Bye(struct soap *soap, struct wsdd__ByeType tdn__Bye, struct wsdd__ResolveType &tdn__ByeResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tdn__Probe */
int __tdn__Probe(struct soap *soap, struct wsdd__ProbeType tdn__Probe, struct wsdd__ProbeMatchesType &tdn__ProbeResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetServices */
int __tds__GetServices(struct soap *soap, _tds__GetServices *tds__GetServices, _tds__GetServicesResponse &tds__GetServicesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetServiceCapabilities */
int __tds__GetServiceCapabilities(struct soap *soap, _tds__GetServiceCapabilities *tds__GetServiceCapabilities, _tds__GetServiceCapabilitiesResponse &tds__GetServiceCapabilitiesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetDeviceInformation */
int __tds__GetDeviceInformation(struct soap *soap, _tds__GetDeviceInformation *tds__GetDeviceInformation, _tds__GetDeviceInformationResponse &tds__GetDeviceInformationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetSystemDateAndTime */
int __tds__SetSystemDateAndTime(struct soap *soap, _tds__SetSystemDateAndTime *tds__SetSystemDateAndTime, _tds__SetSystemDateAndTimeResponse &tds__SetSystemDateAndTimeResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetSystemDateAndTime */
int __tds__GetSystemDateAndTime(struct soap *soap, _tds__GetSystemDateAndTime *tds__GetSystemDateAndTime, _tds__GetSystemDateAndTimeResponse &tds__GetSystemDateAndTimeResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetSystemFactoryDefault */
int __tds__SetSystemFactoryDefault(struct soap *soap, _tds__SetSystemFactoryDefault *tds__SetSystemFactoryDefault, _tds__SetSystemFactoryDefaultResponse &tds__SetSystemFactoryDefaultResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__UpgradeSystemFirmware */
int __tds__UpgradeSystemFirmware(struct soap *soap, _tds__UpgradeSystemFirmware *tds__UpgradeSystemFirmware, _tds__UpgradeSystemFirmwareResponse &tds__UpgradeSystemFirmwareResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SystemReboot */
int __tds__SystemReboot(struct soap *soap, _tds__SystemReboot *tds__SystemReboot, _tds__SystemRebootResponse &tds__SystemRebootResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__RestoreSystem */
int __tds__RestoreSystem(struct soap *soap, _tds__RestoreSystem *tds__RestoreSystem, _tds__RestoreSystemResponse &tds__RestoreSystemResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetSystemBackup */
int __tds__GetSystemBackup(struct soap *soap, _tds__GetSystemBackup *tds__GetSystemBackup, _tds__GetSystemBackupResponse &tds__GetSystemBackupResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetSystemLog */
int __tds__GetSystemLog(struct soap *soap, _tds__GetSystemLog *tds__GetSystemLog, _tds__GetSystemLogResponse &tds__GetSystemLogResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetSystemSupportInformation */
int __tds__GetSystemSupportInformation(struct soap *soap, _tds__GetSystemSupportInformation *tds__GetSystemSupportInformation, _tds__GetSystemSupportInformationResponse &tds__GetSystemSupportInformationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetScopes */
int __tds__GetScopes(struct soap *soap, _tds__GetScopes *tds__GetScopes, _tds__GetScopesResponse &tds__GetScopesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetScopes */
int __tds__SetScopes(struct soap *soap, _tds__SetScopes *tds__SetScopes, _tds__SetScopesResponse &tds__SetScopesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__AddScopes */
int __tds__AddScopes(struct soap *soap, _tds__AddScopes *tds__AddScopes, _tds__AddScopesResponse &tds__AddScopesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__RemoveScopes */
int __tds__RemoveScopes(struct soap *soap, _tds__RemoveScopes *tds__RemoveScopes, _tds__RemoveScopesResponse &tds__RemoveScopesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetDiscoveryMode */
int __tds__GetDiscoveryMode(struct soap *soap, _tds__GetDiscoveryMode *tds__GetDiscoveryMode, _tds__GetDiscoveryModeResponse &tds__GetDiscoveryModeResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetDiscoveryMode */
int __tds__SetDiscoveryMode(struct soap *soap, _tds__SetDiscoveryMode *tds__SetDiscoveryMode, _tds__SetDiscoveryModeResponse &tds__SetDiscoveryModeResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetRemoteDiscoveryMode */
int __tds__GetRemoteDiscoveryMode(struct soap *soap, _tds__GetRemoteDiscoveryMode *tds__GetRemoteDiscoveryMode, _tds__GetRemoteDiscoveryModeResponse &tds__GetRemoteDiscoveryModeResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetRemoteDiscoveryMode */
int __tds__SetRemoteDiscoveryMode(struct soap *soap, _tds__SetRemoteDiscoveryMode *tds__SetRemoteDiscoveryMode, _tds__SetRemoteDiscoveryModeResponse &tds__SetRemoteDiscoveryModeResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetDPAddresses */
int __tds__GetDPAddresses(struct soap *soap, _tds__GetDPAddresses *tds__GetDPAddresses, _tds__GetDPAddressesResponse &tds__GetDPAddressesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetEndpointReference */
int __tds__GetEndpointReference(struct soap *soap, _tds__GetEndpointReference *tds__GetEndpointReference, _tds__GetEndpointReferenceResponse &tds__GetEndpointReferenceResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetRemoteUser */
int __tds__GetRemoteUser(struct soap *soap, _tds__GetRemoteUser *tds__GetRemoteUser, _tds__GetRemoteUserResponse &tds__GetRemoteUserResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetRemoteUser */
int __tds__SetRemoteUser(struct soap *soap, _tds__SetRemoteUser *tds__SetRemoteUser, _tds__SetRemoteUserResponse &tds__SetRemoteUserResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetUsers */
int __tds__GetUsers(struct soap *soap, _tds__GetUsers *tds__GetUsers, _tds__GetUsersResponse &tds__GetUsersResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__CreateUsers */
int __tds__CreateUsers(struct soap *soap, _tds__CreateUsers *tds__CreateUsers, _tds__CreateUsersResponse &tds__CreateUsersResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__DeleteUsers */
int __tds__DeleteUsers(struct soap *soap, _tds__DeleteUsers *tds__DeleteUsers, _tds__DeleteUsersResponse &tds__DeleteUsersResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetUser */
int __tds__SetUser(struct soap *soap, _tds__SetUser *tds__SetUser, _tds__SetUserResponse &tds__SetUserResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetWsdlUrl */
int __tds__GetWsdlUrl(struct soap *soap, _tds__GetWsdlUrl *tds__GetWsdlUrl, _tds__GetWsdlUrlResponse &tds__GetWsdlUrlResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetCapabilities */
int __tds__GetCapabilities(struct soap *soap, _tds__GetCapabilities *tds__GetCapabilities, _tds__GetCapabilitiesResponse &tds__GetCapabilitiesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetDPAddresses */
int __tds__SetDPAddresses(struct soap *soap, _tds__SetDPAddresses *tds__SetDPAddresses, _tds__SetDPAddressesResponse &tds__SetDPAddressesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetHostname */
int __tds__GetHostname(struct soap *soap, _tds__GetHostname *tds__GetHostname, _tds__GetHostnameResponse &tds__GetHostnameResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetHostname */
int __tds__SetHostname(struct soap *soap, _tds__SetHostname *tds__SetHostname, _tds__SetHostnameResponse &tds__SetHostnameResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetHostnameFromDHCP */
int __tds__SetHostnameFromDHCP(struct soap *soap, _tds__SetHostnameFromDHCP *tds__SetHostnameFromDHCP, _tds__SetHostnameFromDHCPResponse &tds__SetHostnameFromDHCPResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetDNS */
int __tds__GetDNS(struct soap *soap, _tds__GetDNS *tds__GetDNS, _tds__GetDNSResponse &tds__GetDNSResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetDNS */
int __tds__SetDNS(struct soap *soap, _tds__SetDNS *tds__SetDNS, _tds__SetDNSResponse &tds__SetDNSResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetNTP */
int __tds__GetNTP(struct soap *soap, _tds__GetNTP *tds__GetNTP, _tds__GetNTPResponse &tds__GetNTPResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetNTP */
int __tds__SetNTP(struct soap *soap, _tds__SetNTP *tds__SetNTP, _tds__SetNTPResponse &tds__SetNTPResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetDynamicDNS */
int __tds__GetDynamicDNS(struct soap *soap, _tds__GetDynamicDNS *tds__GetDynamicDNS, _tds__GetDynamicDNSResponse &tds__GetDynamicDNSResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetDynamicDNS */
int __tds__SetDynamicDNS(struct soap *soap, _tds__SetDynamicDNS *tds__SetDynamicDNS, _tds__SetDynamicDNSResponse &tds__SetDynamicDNSResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetNetworkInterfaces */
int __tds__GetNetworkInterfaces(struct soap *soap, _tds__GetNetworkInterfaces *tds__GetNetworkInterfaces, _tds__GetNetworkInterfacesResponse &tds__GetNetworkInterfacesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetNetworkInterfaces */
int __tds__SetNetworkInterfaces(struct soap *soap, _tds__SetNetworkInterfaces *tds__SetNetworkInterfaces, _tds__SetNetworkInterfacesResponse &tds__SetNetworkInterfacesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetNetworkProtocols */
int __tds__GetNetworkProtocols(struct soap *soap, _tds__GetNetworkProtocols *tds__GetNetworkProtocols, _tds__GetNetworkProtocolsResponse &tds__GetNetworkProtocolsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetNetworkProtocols */
int __tds__SetNetworkProtocols(struct soap *soap, _tds__SetNetworkProtocols *tds__SetNetworkProtocols, _tds__SetNetworkProtocolsResponse &tds__SetNetworkProtocolsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetNetworkDefaultGateway */
int __tds__GetNetworkDefaultGateway(struct soap *soap, _tds__GetNetworkDefaultGateway *tds__GetNetworkDefaultGateway, _tds__GetNetworkDefaultGatewayResponse &tds__GetNetworkDefaultGatewayResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetNetworkDefaultGateway */
int __tds__SetNetworkDefaultGateway(struct soap *soap, _tds__SetNetworkDefaultGateway *tds__SetNetworkDefaultGateway, _tds__SetNetworkDefaultGatewayResponse &tds__SetNetworkDefaultGatewayResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetZeroConfiguration */
int __tds__GetZeroConfiguration(struct soap *soap, _tds__GetZeroConfiguration *tds__GetZeroConfiguration, _tds__GetZeroConfigurationResponse &tds__GetZeroConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetZeroConfiguration */
int __tds__SetZeroConfiguration(struct soap *soap, _tds__SetZeroConfiguration *tds__SetZeroConfiguration, _tds__SetZeroConfigurationResponse &tds__SetZeroConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetIPAddressFilter */
int __tds__GetIPAddressFilter(struct soap *soap, _tds__GetIPAddressFilter *tds__GetIPAddressFilter, _tds__GetIPAddressFilterResponse &tds__GetIPAddressFilterResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetIPAddressFilter */
int __tds__SetIPAddressFilter(struct soap *soap, _tds__SetIPAddressFilter *tds__SetIPAddressFilter, _tds__SetIPAddressFilterResponse &tds__SetIPAddressFilterResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__AddIPAddressFilter */
int __tds__AddIPAddressFilter(struct soap *soap, _tds__AddIPAddressFilter *tds__AddIPAddressFilter, _tds__AddIPAddressFilterResponse &tds__AddIPAddressFilterResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__RemoveIPAddressFilter */
int __tds__RemoveIPAddressFilter(struct soap *soap, _tds__RemoveIPAddressFilter *tds__RemoveIPAddressFilter, _tds__RemoveIPAddressFilterResponse &tds__RemoveIPAddressFilterResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetAccessPolicy */
int __tds__GetAccessPolicy(struct soap *soap, _tds__GetAccessPolicy *tds__GetAccessPolicy, _tds__GetAccessPolicyResponse &tds__GetAccessPolicyResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetAccessPolicy */
int __tds__SetAccessPolicy(struct soap *soap, _tds__SetAccessPolicy *tds__SetAccessPolicy, _tds__SetAccessPolicyResponse &tds__SetAccessPolicyResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__CreateCertificate */
int __tds__CreateCertificate(struct soap *soap, _tds__CreateCertificate *tds__CreateCertificate, _tds__CreateCertificateResponse &tds__CreateCertificateResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetCertificates */
int __tds__GetCertificates(struct soap *soap, _tds__GetCertificates *tds__GetCertificates, _tds__GetCertificatesResponse &tds__GetCertificatesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetCertificatesStatus */
int __tds__GetCertificatesStatus(struct soap *soap, _tds__GetCertificatesStatus *tds__GetCertificatesStatus, _tds__GetCertificatesStatusResponse &tds__GetCertificatesStatusResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetCertificatesStatus */
int __tds__SetCertificatesStatus(struct soap *soap, _tds__SetCertificatesStatus *tds__SetCertificatesStatus, _tds__SetCertificatesStatusResponse &tds__SetCertificatesStatusResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__DeleteCertificates */
int __tds__DeleteCertificates(struct soap *soap, _tds__DeleteCertificates *tds__DeleteCertificates, _tds__DeleteCertificatesResponse &tds__DeleteCertificatesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetPkcs10Request */
int __tds__GetPkcs10Request(struct soap *soap, _tds__GetPkcs10Request *tds__GetPkcs10Request, _tds__GetPkcs10RequestResponse &tds__GetPkcs10RequestResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__LoadCertificates */
int __tds__LoadCertificates(struct soap *soap, _tds__LoadCertificates *tds__LoadCertificates, _tds__LoadCertificatesResponse &tds__LoadCertificatesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetClientCertificateMode */
int __tds__GetClientCertificateMode(struct soap *soap, _tds__GetClientCertificateMode *tds__GetClientCertificateMode, _tds__GetClientCertificateModeResponse &tds__GetClientCertificateModeResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetClientCertificateMode */
int __tds__SetClientCertificateMode(struct soap *soap, _tds__SetClientCertificateMode *tds__SetClientCertificateMode, _tds__SetClientCertificateModeResponse &tds__SetClientCertificateModeResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetRelayOutputs */
int __tds__GetRelayOutputs(struct soap *soap, _tds__GetRelayOutputs *tds__GetRelayOutputs, _tds__GetRelayOutputsResponse &tds__GetRelayOutputsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetRelayOutputSettings */
int __tds__SetRelayOutputSettings(struct soap *soap, _tds__SetRelayOutputSettings *tds__SetRelayOutputSettings, _tds__SetRelayOutputSettingsResponse &tds__SetRelayOutputSettingsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetRelayOutputState */
int __tds__SetRelayOutputState(struct soap *soap, _tds__SetRelayOutputState *tds__SetRelayOutputState, _tds__SetRelayOutputStateResponse &tds__SetRelayOutputStateResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SendAuxiliaryCommand */
int __tds__SendAuxiliaryCommand(struct soap *soap, _tds__SendAuxiliaryCommand *tds__SendAuxiliaryCommand, _tds__SendAuxiliaryCommandResponse &tds__SendAuxiliaryCommandResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetCACertificates */
int __tds__GetCACertificates(struct soap *soap, _tds__GetCACertificates *tds__GetCACertificates, _tds__GetCACertificatesResponse &tds__GetCACertificatesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__LoadCertificateWithPrivateKey */
int __tds__LoadCertificateWithPrivateKey(struct soap *soap, _tds__LoadCertificateWithPrivateKey *tds__LoadCertificateWithPrivateKey, _tds__LoadCertificateWithPrivateKeyResponse &tds__LoadCertificateWithPrivateKeyResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetCertificateInformation */
int __tds__GetCertificateInformation(struct soap *soap, _tds__GetCertificateInformation *tds__GetCertificateInformation, _tds__GetCertificateInformationResponse &tds__GetCertificateInformationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__LoadCACertificates */
int __tds__LoadCACertificates(struct soap *soap, _tds__LoadCACertificates *tds__LoadCACertificates, _tds__LoadCACertificatesResponse &tds__LoadCACertificatesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__CreateDot1XConfiguration */
int __tds__CreateDot1XConfiguration(struct soap *soap, _tds__CreateDot1XConfiguration *tds__CreateDot1XConfiguration, _tds__CreateDot1XConfigurationResponse &tds__CreateDot1XConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetDot1XConfiguration */
int __tds__SetDot1XConfiguration(struct soap *soap, _tds__SetDot1XConfiguration *tds__SetDot1XConfiguration, _tds__SetDot1XConfigurationResponse &tds__SetDot1XConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetDot1XConfiguration */
int __tds__GetDot1XConfiguration(struct soap *soap, _tds__GetDot1XConfiguration *tds__GetDot1XConfiguration, _tds__GetDot1XConfigurationResponse &tds__GetDot1XConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetDot1XConfigurations */
int __tds__GetDot1XConfigurations(struct soap *soap, _tds__GetDot1XConfigurations *tds__GetDot1XConfigurations, _tds__GetDot1XConfigurationsResponse &tds__GetDot1XConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__DeleteDot1XConfiguration */
int __tds__DeleteDot1XConfiguration(struct soap *soap, _tds__DeleteDot1XConfiguration *tds__DeleteDot1XConfiguration, _tds__DeleteDot1XConfigurationResponse &tds__DeleteDot1XConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetDot11Capabilities */
int __tds__GetDot11Capabilities(struct soap *soap, _tds__GetDot11Capabilities *tds__GetDot11Capabilities, _tds__GetDot11CapabilitiesResponse &tds__GetDot11CapabilitiesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetDot11Status */
int __tds__GetDot11Status(struct soap *soap, _tds__GetDot11Status *tds__GetDot11Status, _tds__GetDot11StatusResponse &tds__GetDot11StatusResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__ScanAvailableDot11Networks */
int __tds__ScanAvailableDot11Networks(struct soap *soap, _tds__ScanAvailableDot11Networks *tds__ScanAvailableDot11Networks, _tds__ScanAvailableDot11NetworksResponse &tds__ScanAvailableDot11NetworksResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetSystemUris */
int __tds__GetSystemUris(struct soap *soap, _tds__GetSystemUris *tds__GetSystemUris, _tds__GetSystemUrisResponse &tds__GetSystemUrisResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__StartFirmwareUpgrade */
int __tds__StartFirmwareUpgrade(struct soap *soap, _tds__StartFirmwareUpgrade *tds__StartFirmwareUpgrade, _tds__StartFirmwareUpgradeResponse &tds__StartFirmwareUpgradeResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__StartSystemRestore */
int __tds__StartSystemRestore(struct soap *soap, _tds__StartSystemRestore *tds__StartSystemRestore, _tds__StartSystemRestoreResponse &tds__StartSystemRestoreResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetStorageConfigurations */
int __tds__GetStorageConfigurations(struct soap *soap, _tds__GetStorageConfigurations *tds__GetStorageConfigurations, _tds__GetStorageConfigurationsResponse &tds__GetStorageConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__CreateStorageConfiguration */
int __tds__CreateStorageConfiguration(struct soap *soap, _tds__CreateStorageConfiguration *tds__CreateStorageConfiguration, _tds__CreateStorageConfigurationResponse &tds__CreateStorageConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetStorageConfiguration */
int __tds__GetStorageConfiguration(struct soap *soap, _tds__GetStorageConfiguration *tds__GetStorageConfiguration, _tds__GetStorageConfigurationResponse &tds__GetStorageConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetStorageConfiguration */
int __tds__SetStorageConfiguration(struct soap *soap, _tds__SetStorageConfiguration *tds__SetStorageConfiguration, _tds__SetStorageConfigurationResponse &tds__SetStorageConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__DeleteStorageConfiguration */
int __tds__DeleteStorageConfiguration(struct soap *soap, _tds__DeleteStorageConfiguration *tds__DeleteStorageConfiguration, _tds__DeleteStorageConfigurationResponse &tds__DeleteStorageConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__GetGeoLocation */
int __tds__GetGeoLocation(struct soap *soap, _tds__GetGeoLocation *tds__GetGeoLocation, _tds__GetGeoLocationResponse &tds__GetGeoLocationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__SetGeoLocation */
int __tds__SetGeoLocation(struct soap *soap, _tds__SetGeoLocation *tds__SetGeoLocation, _tds__SetGeoLocationResponse &tds__SetGeoLocationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tds__DeleteGeoLocation */
int __tds__DeleteGeoLocation(struct soap *soap, _tds__DeleteGeoLocation *tds__DeleteGeoLocation, _tds__DeleteGeoLocationResponse &tds__DeleteGeoLocationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GetServiceCapabilities */
int __tptz__GetServiceCapabilities(struct soap *soap, _tptz__GetServiceCapabilities *tptz__GetServiceCapabilities, _tptz__GetServiceCapabilitiesResponse &tptz__GetServiceCapabilitiesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GetConfigurations */
int __tptz__GetConfigurations(struct soap *soap, _tptz__GetConfigurations *tptz__GetConfigurations, _tptz__GetConfigurationsResponse &tptz__GetConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GetPresets */
int __tptz__GetPresets(struct soap *soap, _tptz__GetPresets *tptz__GetPresets, _tptz__GetPresetsResponse &tptz__GetPresetsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__SetPreset */
int __tptz__SetPreset(struct soap *soap, _tptz__SetPreset *tptz__SetPreset, _tptz__SetPresetResponse &tptz__SetPresetResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__RemovePreset */
int __tptz__RemovePreset(struct soap *soap, _tptz__RemovePreset *tptz__RemovePreset, _tptz__RemovePresetResponse &tptz__RemovePresetResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GotoPreset */
int __tptz__GotoPreset(struct soap *soap, _tptz__GotoPreset *tptz__GotoPreset, _tptz__GotoPresetResponse &tptz__GotoPresetResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GetStatus */
int __tptz__GetStatus(struct soap *soap, _tptz__GetStatus *tptz__GetStatus, _tptz__GetStatusResponse &tptz__GetStatusResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GetConfiguration */
int __tptz__GetConfiguration(struct soap *soap, _tptz__GetConfiguration *tptz__GetConfiguration, _tptz__GetConfigurationResponse &tptz__GetConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GetNodes */
int __tptz__GetNodes(struct soap *soap, _tptz__GetNodes *tptz__GetNodes, _tptz__GetNodesResponse &tptz__GetNodesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GetNode */
int __tptz__GetNode(struct soap *soap, _tptz__GetNode *tptz__GetNode, _tptz__GetNodeResponse &tptz__GetNodeResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__SetConfiguration */
int __tptz__SetConfiguration(struct soap *soap, _tptz__SetConfiguration *tptz__SetConfiguration, _tptz__SetConfigurationResponse &tptz__SetConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GetConfigurationOptions */
int __tptz__GetConfigurationOptions(struct soap *soap, _tptz__GetConfigurationOptions *tptz__GetConfigurationOptions, _tptz__GetConfigurationOptionsResponse &tptz__GetConfigurationOptionsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GotoHomePosition */
int __tptz__GotoHomePosition(struct soap *soap, _tptz__GotoHomePosition *tptz__GotoHomePosition, _tptz__GotoHomePositionResponse &tptz__GotoHomePositionResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__SetHomePosition */
int __tptz__SetHomePosition(struct soap *soap, _tptz__SetHomePosition *tptz__SetHomePosition, _tptz__SetHomePositionResponse &tptz__SetHomePositionResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__ContinuousMove */
int __tptz__ContinuousMove(struct soap *soap, _tptz__ContinuousMove *tptz__ContinuousMove, _tptz__ContinuousMoveResponse &tptz__ContinuousMoveResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__RelativeMove */
int __tptz__RelativeMove(struct soap *soap, _tptz__RelativeMove *tptz__RelativeMove, _tptz__RelativeMoveResponse &tptz__RelativeMoveResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__SendAuxiliaryCommand */
int __tptz__SendAuxiliaryCommand(struct soap *soap, _tptz__SendAuxiliaryCommand *tptz__SendAuxiliaryCommand, _tptz__SendAuxiliaryCommandResponse &tptz__SendAuxiliaryCommandResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__AbsoluteMove */
int __tptz__AbsoluteMove(struct soap *soap, _tptz__AbsoluteMove *tptz__AbsoluteMove, _tptz__AbsoluteMoveResponse &tptz__AbsoluteMoveResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GeoMove */
int __tptz__GeoMove(struct soap *soap, _tptz__GeoMove *tptz__GeoMove, _tptz__GeoMoveResponse &tptz__GeoMoveResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__Stop */
int __tptz__Stop(struct soap *soap, _tptz__Stop *tptz__Stop, _tptz__StopResponse &tptz__StopResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GetPresetTours */
int __tptz__GetPresetTours(struct soap *soap, _tptz__GetPresetTours *tptz__GetPresetTours, _tptz__GetPresetToursResponse &tptz__GetPresetToursResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GetPresetTour */
int __tptz__GetPresetTour(struct soap *soap, _tptz__GetPresetTour *tptz__GetPresetTour, _tptz__GetPresetTourResponse &tptz__GetPresetTourResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GetPresetTourOptions */
int __tptz__GetPresetTourOptions(struct soap *soap, _tptz__GetPresetTourOptions *tptz__GetPresetTourOptions, _tptz__GetPresetTourOptionsResponse &tptz__GetPresetTourOptionsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__CreatePresetTour */
int __tptz__CreatePresetTour(struct soap *soap, _tptz__CreatePresetTour *tptz__CreatePresetTour, _tptz__CreatePresetTourResponse &tptz__CreatePresetTourResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__ModifyPresetTour */
int __tptz__ModifyPresetTour(struct soap *soap, _tptz__ModifyPresetTour *tptz__ModifyPresetTour, _tptz__ModifyPresetTourResponse &tptz__ModifyPresetTourResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__OperatePresetTour */
int __tptz__OperatePresetTour(struct soap *soap, _tptz__OperatePresetTour *tptz__OperatePresetTour, _tptz__OperatePresetTourResponse &tptz__OperatePresetTourResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__RemovePresetTour */
int __tptz__RemovePresetTour(struct soap *soap, _tptz__RemovePresetTour *tptz__RemovePresetTour, _tptz__RemovePresetTourResponse &tptz__RemovePresetTourResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__GetCompatibleConfigurations */
int __tptz__GetCompatibleConfigurations(struct soap *soap, _tptz__GetCompatibleConfigurations *tptz__GetCompatibleConfigurations, _tptz__GetCompatibleConfigurationsResponse &tptz__GetCompatibleConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __tptz__MoveAndStartTracking */
int __tptz__MoveAndStartTracking(struct soap *soap, _tptz__MoveAndStartTracking *tptz__MoveAndStartTracking, _tptz__MoveAndStartTrackingResponse &tptz__MoveAndStartTrackingResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetServiceCapabilities */
int __trt__GetServiceCapabilities(struct soap *soap, _trt__GetServiceCapabilities *trt__GetServiceCapabilities, _trt__GetServiceCapabilitiesResponse &trt__GetServiceCapabilitiesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetVideoSources */
int __trt__GetVideoSources(struct soap *soap, _trt__GetVideoSources *trt__GetVideoSources, _trt__GetVideoSourcesResponse &trt__GetVideoSourcesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetAudioSources */
int __trt__GetAudioSources(struct soap *soap, _trt__GetAudioSources *trt__GetAudioSources, _trt__GetAudioSourcesResponse &trt__GetAudioSourcesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetAudioOutputs */
int __trt__GetAudioOutputs(struct soap *soap, _trt__GetAudioOutputs *trt__GetAudioOutputs, _trt__GetAudioOutputsResponse &trt__GetAudioOutputsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__CreateProfile */
int __trt__CreateProfile(struct soap *soap, _trt__CreateProfile *trt__CreateProfile, _trt__CreateProfileResponse &trt__CreateProfileResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetProfile */
int __trt__GetProfile(struct soap *soap, _trt__GetProfile *trt__GetProfile, _trt__GetProfileResponse &trt__GetProfileResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetProfiles */
int __trt__GetProfiles(struct soap *soap, _trt__GetProfiles *trt__GetProfiles, _trt__GetProfilesResponse &trt__GetProfilesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__AddVideoEncoderConfiguration */
int __trt__AddVideoEncoderConfiguration(struct soap *soap, _trt__AddVideoEncoderConfiguration *trt__AddVideoEncoderConfiguration, _trt__AddVideoEncoderConfigurationResponse &trt__AddVideoEncoderConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__AddVideoSourceConfiguration */
int __trt__AddVideoSourceConfiguration(struct soap *soap, _trt__AddVideoSourceConfiguration *trt__AddVideoSourceConfiguration, _trt__AddVideoSourceConfigurationResponse &trt__AddVideoSourceConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__AddAudioEncoderConfiguration */
int __trt__AddAudioEncoderConfiguration(struct soap *soap, _trt__AddAudioEncoderConfiguration *trt__AddAudioEncoderConfiguration, _trt__AddAudioEncoderConfigurationResponse &trt__AddAudioEncoderConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__AddAudioSourceConfiguration */
int __trt__AddAudioSourceConfiguration(struct soap *soap, _trt__AddAudioSourceConfiguration *trt__AddAudioSourceConfiguration, _trt__AddAudioSourceConfigurationResponse &trt__AddAudioSourceConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__AddPTZConfiguration */
int __trt__AddPTZConfiguration(struct soap *soap, _trt__AddPTZConfiguration *trt__AddPTZConfiguration, _trt__AddPTZConfigurationResponse &trt__AddPTZConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__AddVideoAnalyticsConfiguration */
int __trt__AddVideoAnalyticsConfiguration(struct soap *soap, _trt__AddVideoAnalyticsConfiguration *trt__AddVideoAnalyticsConfiguration, _trt__AddVideoAnalyticsConfigurationResponse &trt__AddVideoAnalyticsConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__AddMetadataConfiguration */
int __trt__AddMetadataConfiguration(struct soap *soap, _trt__AddMetadataConfiguration *trt__AddMetadataConfiguration, _trt__AddMetadataConfigurationResponse &trt__AddMetadataConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__AddAudioOutputConfiguration */
int __trt__AddAudioOutputConfiguration(struct soap *soap, _trt__AddAudioOutputConfiguration *trt__AddAudioOutputConfiguration, _trt__AddAudioOutputConfigurationResponse &trt__AddAudioOutputConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__AddAudioDecoderConfiguration */
int __trt__AddAudioDecoderConfiguration(struct soap *soap, _trt__AddAudioDecoderConfiguration *trt__AddAudioDecoderConfiguration, _trt__AddAudioDecoderConfigurationResponse &trt__AddAudioDecoderConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__RemoveVideoEncoderConfiguration */
int __trt__RemoveVideoEncoderConfiguration(struct soap *soap, _trt__RemoveVideoEncoderConfiguration *trt__RemoveVideoEncoderConfiguration, _trt__RemoveVideoEncoderConfigurationResponse &trt__RemoveVideoEncoderConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__RemoveVideoSourceConfiguration */
int __trt__RemoveVideoSourceConfiguration(struct soap *soap, _trt__RemoveVideoSourceConfiguration *trt__RemoveVideoSourceConfiguration, _trt__RemoveVideoSourceConfigurationResponse &trt__RemoveVideoSourceConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__RemoveAudioEncoderConfiguration */
int __trt__RemoveAudioEncoderConfiguration(struct soap *soap, _trt__RemoveAudioEncoderConfiguration *trt__RemoveAudioEncoderConfiguration, _trt__RemoveAudioEncoderConfigurationResponse &trt__RemoveAudioEncoderConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__RemoveAudioSourceConfiguration */
int __trt__RemoveAudioSourceConfiguration(struct soap *soap, _trt__RemoveAudioSourceConfiguration *trt__RemoveAudioSourceConfiguration, _trt__RemoveAudioSourceConfigurationResponse &trt__RemoveAudioSourceConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__RemovePTZConfiguration */
int __trt__RemovePTZConfiguration(struct soap *soap, _trt__RemovePTZConfiguration *trt__RemovePTZConfiguration, _trt__RemovePTZConfigurationResponse &trt__RemovePTZConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__RemoveVideoAnalyticsConfiguration */
int __trt__RemoveVideoAnalyticsConfiguration(struct soap *soap, _trt__RemoveVideoAnalyticsConfiguration *trt__RemoveVideoAnalyticsConfiguration, _trt__RemoveVideoAnalyticsConfigurationResponse &trt__RemoveVideoAnalyticsConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__RemoveMetadataConfiguration */
int __trt__RemoveMetadataConfiguration(struct soap *soap, _trt__RemoveMetadataConfiguration *trt__RemoveMetadataConfiguration, _trt__RemoveMetadataConfigurationResponse &trt__RemoveMetadataConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__RemoveAudioOutputConfiguration */
int __trt__RemoveAudioOutputConfiguration(struct soap *soap, _trt__RemoveAudioOutputConfiguration *trt__RemoveAudioOutputConfiguration, _trt__RemoveAudioOutputConfigurationResponse &trt__RemoveAudioOutputConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__RemoveAudioDecoderConfiguration */
int __trt__RemoveAudioDecoderConfiguration(struct soap *soap, _trt__RemoveAudioDecoderConfiguration *trt__RemoveAudioDecoderConfiguration, _trt__RemoveAudioDecoderConfigurationResponse &trt__RemoveAudioDecoderConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__DeleteProfile */
int __trt__DeleteProfile(struct soap *soap, _trt__DeleteProfile *trt__DeleteProfile, _trt__DeleteProfileResponse &trt__DeleteProfileResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetVideoSourceConfigurations */
int __trt__GetVideoSourceConfigurations(struct soap *soap, _trt__GetVideoSourceConfigurations *trt__GetVideoSourceConfigurations, _trt__GetVideoSourceConfigurationsResponse &trt__GetVideoSourceConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetVideoEncoderConfigurations */
int __trt__GetVideoEncoderConfigurations(struct soap *soap, _trt__GetVideoEncoderConfigurations *trt__GetVideoEncoderConfigurations, _trt__GetVideoEncoderConfigurationsResponse &trt__GetVideoEncoderConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetAudioSourceConfigurations */
int __trt__GetAudioSourceConfigurations(struct soap *soap, _trt__GetAudioSourceConfigurations *trt__GetAudioSourceConfigurations, _trt__GetAudioSourceConfigurationsResponse &trt__GetAudioSourceConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetAudioEncoderConfigurations */
int __trt__GetAudioEncoderConfigurations(struct soap *soap, _trt__GetAudioEncoderConfigurations *trt__GetAudioEncoderConfigurations, _trt__GetAudioEncoderConfigurationsResponse &trt__GetAudioEncoderConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetVideoAnalyticsConfigurations */
int __trt__GetVideoAnalyticsConfigurations(struct soap *soap, _trt__GetVideoAnalyticsConfigurations *trt__GetVideoAnalyticsConfigurations, _trt__GetVideoAnalyticsConfigurationsResponse &trt__GetVideoAnalyticsConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetMetadataConfigurations */
int __trt__GetMetadataConfigurations(struct soap *soap, _trt__GetMetadataConfigurations *trt__GetMetadataConfigurations, _trt__GetMetadataConfigurationsResponse &trt__GetMetadataConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetAudioOutputConfigurations */
int __trt__GetAudioOutputConfigurations(struct soap *soap, _trt__GetAudioOutputConfigurations *trt__GetAudioOutputConfigurations, _trt__GetAudioOutputConfigurationsResponse &trt__GetAudioOutputConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetAudioDecoderConfigurations */
int __trt__GetAudioDecoderConfigurations(struct soap *soap, _trt__GetAudioDecoderConfigurations *trt__GetAudioDecoderConfigurations, _trt__GetAudioDecoderConfigurationsResponse &trt__GetAudioDecoderConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetVideoSourceConfiguration */
int __trt__GetVideoSourceConfiguration(struct soap *soap, _trt__GetVideoSourceConfiguration *trt__GetVideoSourceConfiguration, _trt__GetVideoSourceConfigurationResponse &trt__GetVideoSourceConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetVideoEncoderConfiguration */
int __trt__GetVideoEncoderConfiguration(struct soap *soap, _trt__GetVideoEncoderConfiguration *trt__GetVideoEncoderConfiguration, _trt__GetVideoEncoderConfigurationResponse &trt__GetVideoEncoderConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetAudioSourceConfiguration */
int __trt__GetAudioSourceConfiguration(struct soap *soap, _trt__GetAudioSourceConfiguration *trt__GetAudioSourceConfiguration, _trt__GetAudioSourceConfigurationResponse &trt__GetAudioSourceConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetAudioEncoderConfiguration */
int __trt__GetAudioEncoderConfiguration(struct soap *soap, _trt__GetAudioEncoderConfiguration *trt__GetAudioEncoderConfiguration, _trt__GetAudioEncoderConfigurationResponse &trt__GetAudioEncoderConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetVideoAnalyticsConfiguration */
int __trt__GetVideoAnalyticsConfiguration(struct soap *soap, _trt__GetVideoAnalyticsConfiguration *trt__GetVideoAnalyticsConfiguration, _trt__GetVideoAnalyticsConfigurationResponse &trt__GetVideoAnalyticsConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetMetadataConfiguration */
int __trt__GetMetadataConfiguration(struct soap *soap, _trt__GetMetadataConfiguration *trt__GetMetadataConfiguration, _trt__GetMetadataConfigurationResponse &trt__GetMetadataConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetAudioOutputConfiguration */
int __trt__GetAudioOutputConfiguration(struct soap *soap, _trt__GetAudioOutputConfiguration *trt__GetAudioOutputConfiguration, _trt__GetAudioOutputConfigurationResponse &trt__GetAudioOutputConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetAudioDecoderConfiguration */
int __trt__GetAudioDecoderConfiguration(struct soap *soap, _trt__GetAudioDecoderConfiguration *trt__GetAudioDecoderConfiguration, _trt__GetAudioDecoderConfigurationResponse &trt__GetAudioDecoderConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetCompatibleVideoEncoderConfigurations */
int __trt__GetCompatibleVideoEncoderConfigurations(struct soap *soap, _trt__GetCompatibleVideoEncoderConfigurations *trt__GetCompatibleVideoEncoderConfigurations, _trt__GetCompatibleVideoEncoderConfigurationsResponse &trt__GetCompatibleVideoEncoderConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetCompatibleVideoSourceConfigurations */
int __trt__GetCompatibleVideoSourceConfigurations(struct soap *soap, _trt__GetCompatibleVideoSourceConfigurations *trt__GetCompatibleVideoSourceConfigurations, _trt__GetCompatibleVideoSourceConfigurationsResponse &trt__GetCompatibleVideoSourceConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetCompatibleAudioEncoderConfigurations */
int __trt__GetCompatibleAudioEncoderConfigurations(struct soap *soap, _trt__GetCompatibleAudioEncoderConfigurations *trt__GetCompatibleAudioEncoderConfigurations, _trt__GetCompatibleAudioEncoderConfigurationsResponse &trt__GetCompatibleAudioEncoderConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetCompatibleAudioSourceConfigurations */
int __trt__GetCompatibleAudioSourceConfigurations(struct soap *soap, _trt__GetCompatibleAudioSourceConfigurations *trt__GetCompatibleAudioSourceConfigurations, _trt__GetCompatibleAudioSourceConfigurationsResponse &trt__GetCompatibleAudioSourceConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetCompatibleVideoAnalyticsConfigurations */
int __trt__GetCompatibleVideoAnalyticsConfigurations(struct soap *soap, _trt__GetCompatibleVideoAnalyticsConfigurations *trt__GetCompatibleVideoAnalyticsConfigurations, _trt__GetCompatibleVideoAnalyticsConfigurationsResponse &trt__GetCompatibleVideoAnalyticsConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetCompatibleMetadataConfigurations */
int __trt__GetCompatibleMetadataConfigurations(struct soap *soap, _trt__GetCompatibleMetadataConfigurations *trt__GetCompatibleMetadataConfigurations, _trt__GetCompatibleMetadataConfigurationsResponse &trt__GetCompatibleMetadataConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetCompatibleAudioOutputConfigurations */
int __trt__GetCompatibleAudioOutputConfigurations(struct soap *soap, _trt__GetCompatibleAudioOutputConfigurations *trt__GetCompatibleAudioOutputConfigurations, _trt__GetCompatibleAudioOutputConfigurationsResponse &trt__GetCompatibleAudioOutputConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetCompatibleAudioDecoderConfigurations */
int __trt__GetCompatibleAudioDecoderConfigurations(struct soap *soap, _trt__GetCompatibleAudioDecoderConfigurations *trt__GetCompatibleAudioDecoderConfigurations, _trt__GetCompatibleAudioDecoderConfigurationsResponse &trt__GetCompatibleAudioDecoderConfigurationsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__SetVideoSourceConfiguration */
int __trt__SetVideoSourceConfiguration(struct soap *soap, _trt__SetVideoSourceConfiguration *trt__SetVideoSourceConfiguration, _trt__SetVideoSourceConfigurationResponse &trt__SetVideoSourceConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__SetVideoEncoderConfiguration */
int __trt__SetVideoEncoderConfiguration(struct soap *soap, _trt__SetVideoEncoderConfiguration *trt__SetVideoEncoderConfiguration, _trt__SetVideoEncoderConfigurationResponse &trt__SetVideoEncoderConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__SetAudioSourceConfiguration */
int __trt__SetAudioSourceConfiguration(struct soap *soap, _trt__SetAudioSourceConfiguration *trt__SetAudioSourceConfiguration, _trt__SetAudioSourceConfigurationResponse &trt__SetAudioSourceConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__SetAudioEncoderConfiguration */
int __trt__SetAudioEncoderConfiguration(struct soap *soap, _trt__SetAudioEncoderConfiguration *trt__SetAudioEncoderConfiguration, _trt__SetAudioEncoderConfigurationResponse &trt__SetAudioEncoderConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__SetVideoAnalyticsConfiguration */
int __trt__SetVideoAnalyticsConfiguration(struct soap *soap, _trt__SetVideoAnalyticsConfiguration *trt__SetVideoAnalyticsConfiguration, _trt__SetVideoAnalyticsConfigurationResponse &trt__SetVideoAnalyticsConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__SetMetadataConfiguration */
int __trt__SetMetadataConfiguration(struct soap *soap, _trt__SetMetadataConfiguration *trt__SetMetadataConfiguration, _trt__SetMetadataConfigurationResponse &trt__SetMetadataConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__SetAudioOutputConfiguration */
int __trt__SetAudioOutputConfiguration(struct soap *soap, _trt__SetAudioOutputConfiguration *trt__SetAudioOutputConfiguration, _trt__SetAudioOutputConfigurationResponse &trt__SetAudioOutputConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__SetAudioDecoderConfiguration */
int __trt__SetAudioDecoderConfiguration(struct soap *soap, _trt__SetAudioDecoderConfiguration *trt__SetAudioDecoderConfiguration, _trt__SetAudioDecoderConfigurationResponse &trt__SetAudioDecoderConfigurationResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetVideoSourceConfigurationOptions */
int __trt__GetVideoSourceConfigurationOptions(struct soap *soap, _trt__GetVideoSourceConfigurationOptions *trt__GetVideoSourceConfigurationOptions, _trt__GetVideoSourceConfigurationOptionsResponse &trt__GetVideoSourceConfigurationOptionsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetVideoEncoderConfigurationOptions */
int __trt__GetVideoEncoderConfigurationOptions(struct soap *soap, _trt__GetVideoEncoderConfigurationOptions *trt__GetVideoEncoderConfigurationOptions, _trt__GetVideoEncoderConfigurationOptionsResponse &trt__GetVideoEncoderConfigurationOptionsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetAudioSourceConfigurationOptions */
int __trt__GetAudioSourceConfigurationOptions(struct soap *soap, _trt__GetAudioSourceConfigurationOptions *trt__GetAudioSourceConfigurationOptions, _trt__GetAudioSourceConfigurationOptionsResponse &trt__GetAudioSourceConfigurationOptionsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetAudioEncoderConfigurationOptions */
int __trt__GetAudioEncoderConfigurationOptions(struct soap *soap, _trt__GetAudioEncoderConfigurationOptions *trt__GetAudioEncoderConfigurationOptions, _trt__GetAudioEncoderConfigurationOptionsResponse &trt__GetAudioEncoderConfigurationOptionsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetMetadataConfigurationOptions */
int __trt__GetMetadataConfigurationOptions(struct soap *soap, _trt__GetMetadataConfigurationOptions *trt__GetMetadataConfigurationOptions, _trt__GetMetadataConfigurationOptionsResponse &trt__GetMetadataConfigurationOptionsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetAudioOutputConfigurationOptions */
int __trt__GetAudioOutputConfigurationOptions(struct soap *soap, _trt__GetAudioOutputConfigurationOptions *trt__GetAudioOutputConfigurationOptions, _trt__GetAudioOutputConfigurationOptionsResponse &trt__GetAudioOutputConfigurationOptionsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetAudioDecoderConfigurationOptions */
int __trt__GetAudioDecoderConfigurationOptions(struct soap *soap, _trt__GetAudioDecoderConfigurationOptions *trt__GetAudioDecoderConfigurationOptions, _trt__GetAudioDecoderConfigurationOptionsResponse &trt__GetAudioDecoderConfigurationOptionsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetGuaranteedNumberOfVideoEncoderInstances */
int __trt__GetGuaranteedNumberOfVideoEncoderInstances(struct soap *soap, _trt__GetGuaranteedNumberOfVideoEncoderInstances *trt__GetGuaranteedNumberOfVideoEncoderInstances, _trt__GetGuaranteedNumberOfVideoEncoderInstancesResponse &trt__GetGuaranteedNumberOfVideoEncoderInstancesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetStreamUri */
int __trt__GetStreamUri(struct soap *soap, _trt__GetStreamUri *trt__GetStreamUri, _trt__GetStreamUriResponse &trt__GetStreamUriResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__StartMulticastStreaming */
int __trt__StartMulticastStreaming(struct soap *soap, _trt__StartMulticastStreaming *trt__StartMulticastStreaming, _trt__StartMulticastStreamingResponse &trt__StartMulticastStreamingResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__StopMulticastStreaming */
int __trt__StopMulticastStreaming(struct soap *soap, _trt__StopMulticastStreaming *trt__StopMulticastStreaming, _trt__StopMulticastStreamingResponse &trt__StopMulticastStreamingResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__SetSynchronizationPoint */
int __trt__SetSynchronizationPoint(struct soap *soap, _trt__SetSynchronizationPoint *trt__SetSynchronizationPoint, _trt__SetSynchronizationPointResponse &trt__SetSynchronizationPointResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetSnapshotUri */
int __trt__GetSnapshotUri(struct soap *soap, _trt__GetSnapshotUri *trt__GetSnapshotUri, _trt__GetSnapshotUriResponse &trt__GetSnapshotUriResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetVideoSourceModes */
int __trt__GetVideoSourceModes(struct soap *soap, _trt__GetVideoSourceModes *trt__GetVideoSourceModes, _trt__GetVideoSourceModesResponse &trt__GetVideoSourceModesResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__SetVideoSourceMode */
int __trt__SetVideoSourceMode(struct soap *soap, _trt__SetVideoSourceMode *trt__SetVideoSourceMode, _trt__SetVideoSourceModeResponse &trt__SetVideoSourceModeResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetOSDs */
int __trt__GetOSDs(struct soap *soap, _trt__GetOSDs *trt__GetOSDs, _trt__GetOSDsResponse &trt__GetOSDsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetOSD */
int __trt__GetOSD(struct soap *soap, _trt__GetOSD *trt__GetOSD, _trt__GetOSDResponse &trt__GetOSDResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__GetOSDOptions */
int __trt__GetOSDOptions(struct soap *soap, _trt__GetOSDOptions *trt__GetOSDOptions, _trt__GetOSDOptionsResponse &trt__GetOSDOptionsResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__SetOSD */
int __trt__SetOSD(struct soap *soap, _trt__SetOSD *trt__SetOSD, _trt__SetOSDResponse &trt__SetOSDResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__CreateOSD */
int __trt__CreateOSD(struct soap *soap, _trt__CreateOSD *trt__CreateOSD, _trt__CreateOSDResponse &trt__CreateOSDResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}


/** Auto-test server operation __trt__DeleteOSD */
int __trt__DeleteOSD(struct soap *soap, _trt__DeleteOSD *trt__DeleteOSD, _trt__DeleteOSDResponse &trt__DeleteOSDResponse)
{
	(void)soap; /* appease -Wall -Werror */
	/* Return response with default data and some values copied from the request */
	return SOAP_OK;
}
